export const roles = {
  ROLE_SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_MODERATOR: 'ROLE_MODERATOR',
  ROLE_EDITOR: 'ROLE_EDITOR',
  ROLE_AUTHOR: 'ROLE_AUTHOR',
  ROLE_MINECRAFT: 'ROLE_MINECRAFT',
  ROLE_MINECRAFT_ADMIN: 'ROLE_MINECRAFT_ADMIN',
  ROLE_MINECRAFT_MODERATOR: 'ROLE_MINECRAFT_MODERATOR',
  ROLE_USER: 'ROLE_USER'
};

export const rolesTrans = {
  ROLE_SUPER_ADMIN: 'super_admin',
  ROLE_ADMIN: 'admin',
  ROLE_MODERATOR: 'moderator',
  ROLE_EDITOR: 'editor',
  ROLE_AUTHOR: 'author',
  ROLE_MINECRAFT: 'minecraft',
  ROLE_MINECRAFT_ADMIN: 'minecraft_admin',
  ROLE_MINECRAFT_MODERATOR: 'minecraft_moderator',
  ROLE_USER: 'user'
};
