name: 📦 1 - Create a release on merge

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.5.1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          release-type: node
          default-branch: main
  deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACECUBE_WEBAPP }}'
          channelId: live
          projectId: spacecube-webapp # PROJECT_ID_FIREBASE
          target: spacecube-beta #BETA
# Remove this after deploy prod
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACECUBE_WEBAPP }}'
          channelId: live
          projectId: spacecube-webapp # PROJECT_ID_FIREBASE
          target: spacecube-webapp #PROD
